-- MySQL Script generated by MySQL Workbench
-- 2017年08月11日 星期五 10时39分47秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xkpdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `xkpdb`;

-- -----------------------------------------------------
-- Schema xkpdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xkpdb`
  DEFAULT CHARACTER SET utf8;
USE `xkpdb`;

-- -----------------------------------------------------
-- Table `xkpdb`.`xkp_academy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xkpdb`.`xkp_academy`
(
  `system_id` INT UNSIGNED NOT NULL AUTO_INCREMENT
    COMMENT '主键',
  `name`      VARCHAR(15)  NULL DEFAULT NULL
    COMMENT '学院名称',
  PRIMARY KEY (`system_id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `xkpdb`.`xkp_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xkpdb`.`xkp_class`
(
  `system_id`    INT UNSIGNED NOT NULL AUTO_INCREMENT
    COMMENT '主键',
  `specialty_id` INT UNSIGNED NULL DEFAULT NULL
    COMMENT '专业主键',
  `grade`        CHAR(4)      NULL DEFAULT NULL
    COMMENT '年级',
  `name`         VARCHAR(30)  NULL DEFAULT NULL
    COMMENT '班级名称',
  PRIMARY KEY (`system_id`),
  INDEX `uq_class_specialty_grade` (`specialty_id` ASC, `grade` ASC)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `xkpdb`.`xkp_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xkpdb`.`xkp_course`
(
  `system_id` INT UNSIGNED NOT NULL AUTO_INCREMENT
    COMMENT '主键',
  `class_id`  INT UNSIGNED NULL     DEFAULT NULL
    COMMENT '班级主键',
  `credit`    FLOAT        NULL     DEFAULT NULL
    COMMENT '学分',
  `name`      VARCHAR(30)  NULL     DEFAULT NULL
    COMMENT '课程名称',
  `type`      TINYINT(1)   NOT NULL DEFAULT '0'
    COMMENT '0 考察,1 考试',
  PRIMARY KEY (`system_id`),
  INDEX `index2` (`class_id` ASC)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `xkpdb`.`xkp_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xkp_history`
(
  `system_id`      INT UNSIGNED NOT NULL AUTO_INCREMENT
    COMMENT '主键',
  `academy_id`     INT UNSIGNED DEFAULT NULL
    COMMENT '学院id',
  `academy_name`   VARCHAR(15)  DEFAULT NULL
    COMMENT '学院名称',
  `specialty_id`   INT UNSIGNED DEFAULT NULL
    COMMENT '专业id',
  `specialty_name` VARCHAR(40)  DEFAULT NULL
    COMMENT '专业名称',
  `class_id`       INT UNSIGNED DEFAULT NULL
    COMMENT '班级id',
  `class_name`     VARCHAR(30)  DEFAULT NULL
    COMMENT '班级名称',
  `grade`          CHAR(4)      DEFAULT NULL
    COMMENT '年级',
  `title_date`     VARCHAR(45)  DEFAULT NULL
    COMMENT '标题时间',
  `courses`        JSON         DEFAULT NULL
    COMMENT '课程信息',
  `benchmark_data` JSON         DEFAULT NULL
    COMMENT '大表数据',
  PRIMARY KEY (`system_id`),
  UNIQUE KEY `index_query` (`academy_id`, `specialty_id`, `class_id`, `grade`, `title_date`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET utf8;

-- -----------------------------------------------------
-- Table `xkpdb`.`xkp_manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xkpdb`.`xkp_manager`
(
  `system_id`    INT UNSIGNED NOT NULL AUTO_INCREMENT
    COMMENT '主键',
  `academy_id`   INT UNSIGNED NULL     DEFAULT NULL
    COMMENT '学院id',
  `specialty_id` INT UNSIGNED NULL     DEFAULT NULL
    COMMENT '专业id',
  `class_id`     INT UNSIGNED NULL     DEFAULT NULL
    COMMENT '班级id',
  `status`       TINYINT(1)   NOT NULL DEFAULT '0'
    COMMENT '0 无效,1 有效',
  `type`         CHAR(1)      NULL     DEFAULT NULL
    COMMENT 'A 管理员 | B 学院 | C 学生',
  `grade`        CHAR(4)      NULL     DEFAULT NULL
    COMMENT '年级',
  `token`        CHAR(33)     NULL     DEFAULT NULL
    COMMENT '登录token',
  `username`     VARCHAR(15)  NULL     DEFAULT NULL
    COMMENT '用户名',
  `password`     VARCHAR(20)  NULL     DEFAULT NULL
    COMMENT '密码',
  PRIMARY KEY (`system_id`),
  UNIQUE INDEX `uq_manager_username` (`username` ASC),
  KEY `index_token` (`token`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `xkpdb`.`xkp_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xkpdb`.`xkp_score`
(
  `student_id`  INT UNSIGNED DEFAULT NULL
    COMMENT '学生id',
  `course_id`   INT UNSIGNED DEFAULT NULL
    COMMENT '课程id',
  `type`        TINYINT(1)   DEFAULT NULL
    COMMENT '0 考察,1 考试',
  `examination` FLOAT        DEFAULT NULL
    COMMENT '考试分数',
  `inspection`  VARCHAR(3)   DEFAULT NULL
    COMMENT '考察成绩',
  UNIQUE KEY `index1` (`student_id`, `course_id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `xkpdb`.`xkp_specialty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xkpdb`.`xkp_specialty`
(
  `system_id`  INT UNSIGNED NOT NULL AUTO_INCREMENT
    COMMENT '主键',
  `academy_id` INT UNSIGNED NULL DEFAULT NULL
    COMMENT '学院主键',
  `name`       VARCHAR(40)  NULL DEFAULT NULL
    COMMENT '专业名称',
  PRIMARY KEY (`system_id`)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `xkpdb`.`xkp_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xkpdb`.`xkp_student`
(
  `system_id`      INT UNSIGNED NOT NULL AUTO_INCREMENT
    COMMENT '主键',
  `class_id`       INT UNSIGNED NULL DEFAULT NULL
    COMMENT '班级主键',
  `student_number` CHAR(10)     NOT NULL
    COMMENT '学号',
  `behavior`       CHAR(1)      NULL DEFAULT '中'
    COMMENT '操行评等',
  `moral`          FLOAT        NULL DEFAULT '0'
    COMMENT '德育',
  `activity`       FLOAT        NULL DEFAULT '0'
    COMMENT '文体',
  `duty`           FLOAT        NULL DEFAULT '0'
    COMMENT '职务',
  `academic`       FLOAT        NULL DEFAULT '0'
    COMMENT '学术',
  `name`           VARCHAR(20)  NULL DEFAULT NULL
    COMMENT '姓名',
  `duty_desc`      VARCHAR(40)  NULL DEFAULT NULL
    COMMENT '职务说明',
  `academic_desc`  VARCHAR(50)  NULL DEFAULT NULL
    COMMENT '学术说明',
  PRIMARY KEY (`system_id`),
  UNIQUE INDEX `uq_student_number` USING BTREE (`student_number` ASC),
  INDEX `id_student_class` (`class_id` ASC)
)
  ENGINE = InnoDB
  DEFAULT CHARACTER SET = utf8;


USE `xkpdb`;
DELIMITER $$

USE `xkpdb`$$
CREATE
  DEFINER =`root`@`localhost`
  TRIGGER `xkpdb`.`trigger_delete_class`
  AFTER DELETE
  ON `xkpdb`.`xkp_class`
  FOR EACH ROW
BEGIN
  DELETE
  FROM xkpdb.xkp_student
  WHERE class_id = OLD.system_id;
  DELETE
  FROM xkpdb.xkp_manager
  WHERE class_id = OLD.system_id;
  DELETE
  FROM xkpdb.xkp_course
  WHERE class_id = OLD.system_id;
END$$

USE `xkpdb`$$
CREATE
  DEFINER =`root`@`localhost`
  TRIGGER `xkpdb`.`trigger_delete_course`
  AFTER DELETE
  ON `xkpdb`.`xkp_course`
  FOR EACH ROW
BEGIN
  DELETE
  FROM xkpdb.xkp_score
  WHERE course_id = OLD.system_id;
END$$

USE `xkpdb`$$
CREATE
  DEFINER =`root`@`localhost`
  TRIGGER `xkpdb`.`trigger_delete_specialty`
  AFTER DELETE
  ON `xkpdb`.`xkp_specialty`
  FOR EACH ROW
BEGIN
  DELETE
  FROM xkp_class
  WHERE specialty_id = OLD.system_id;
END$$

DELIMITER ;

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
